version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - ./:/app
    ports:
      - "1234:1234"  # Port for GDB/LLDB debugging
    cap_add:
      - SYS_PTRACE  # Required for debugging
    security_opt:
      - seccomp:unconfined  # Allows debugging
    tty: true
    stdin_open: true 